//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KabMan.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("●")]
        public string PasswordChar {
            get {
                return ((string)(this["PasswordChar"]));
            }
            set {
                this["PasswordChar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SAN_Switch_TUI.xls")]
        public string ImportSwitchFileName {
            get {
                return ((string)(this["ImportSwitchFileName"]));
            }
            set {
                this["ImportSwitchFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SAN_Server_TUI.xls")]
        public string ImportServerFileName {
            get {
                return ((string)(this["ImportServerFileName"]));
            }
            set {
                this["ImportServerFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SAN_DASD_TUI.xls")]
        public string ImportDasdFileName {
            get {
                return ((string)(this["ImportDasdFileName"]));
            }
            set {
                this["ImportDasdFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{No:No};{Name:Name};{OS:Operating System};{LcUrm:URM LC};{Blech:BLECH};{Trunk:TRU" +
            "NK};{VtPort:VT PORT};{UrmUrm:URM URM}")]
        public string ImportServerPageColumns {
            get {
                return ((string)(this["ImportServerPageColumns"]));
            }
            set {
                this["ImportServerPageColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{No:No};{Name:Name};{Model:Model};{Port:Port};{LcUrm:URM LC};{Blech:BLECH};{Trunk" +
            ":TRUNK};{VtPort:VT PORT};{UrmUrm:URM URM}")]
        public string ImportDasdPageColumns {
            get {
                return ((string)(this["ImportDasdPageColumns"]));
            }
            set {
                this["ImportDasdPageColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{No:No};{Name:Name};{Model:Model};{Port:Port};{LcUrm:URM LC};{Blech:BLECH};{Trunk" +
            ":TRUNK};{VtPort:VT PORT};{UrmUrm:URM URM};{ConnectionName:Connection Name}")]
        public string ImportSwitchPageColumns {
            get {
                return ((string)(this["ImportSwitchPageColumns"]));
            }
            set {
                this["ImportSwitchPageColumns"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ORION\\SQL2008; Initial Catalog=KabMan; Integrated Security=True")]
        public string KabManConnectionString {
            get {
                return ((string)(this["KabManConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SAN_DCC_TUI.xls")]
        public string ImportDccFileName {
            get {
                return ((string)(this["ImportDccFileName"]));
            }
            set {
                this["ImportDccFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{No:No};{Name:Name};{LcUrm:URM LC};{VtPort1:VT PORT1};{Trunk:TRUNK};{VtPort2:VT P" +
            "ORT2};{UrmUrm:URM URM}")]
        public string ImportDccPageColumns {
            get {
                return ((string)(this["ImportDccPageColumns"]));
            }
            set {
                this["ImportDccPageColumns"] = value;
            }
        }
    }
}
